name: CD

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Deploy AWS CDK Typescript Stack
    runs-on: ubuntu-latest
    steps:
      - name: Initiated By User
        run: echo $GITHUB_ACTOR

      - name: Check Out Code
        uses: actions/checkout@v3.1.0

      - name: Install Node
        uses: actions/setup-node@v3.5.0

      - name: Install Dependencies
        run: npm ci

      # Run npm ci in the src directory
      - name: Install dependencies in cdk-deployment directory
        working-directory: ./cdk-deployment
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Build CDK Stack
        working-directory: ./cdk-deployment
        run: npm run build

      - name: Deploy AWS CDK Stack
        working-directory: ./cdk-deployment
        run: "npx cdk deploy ValApp-cdk-is-subfolder --ci --require-approval never --no-asset-metadata"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"